# Generated by Django 4.2.1 on 2025-07-20 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelexport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('batch_number', models.CharField(max_length=100)),
                ('section', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
