# Generated by Django 4.2.1 on 2025-07-31 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excelexport', '0003_sampleparameters_scaleloadmeasurements_watersystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_per_meter', models.FloatField(help_text='Mass per meter (kg/m)', validators=[django.core.validators.MinValueValidator(0)])),
                ('cross_section_area', models.FloatField(help_text='Cross section area (mm²)', validators=[django.core.validators.MinValueValidator(0)])),
                ('yield_machine_reading', models.FloatField(help_text='Yield load machine reading (kgf)', validators=[django.core.validators.MinValueValidator(0)])),
                ('tensile_machine_reading', models.FloatField(help_text='Tensile load machine reading (kgf)', validators=[django.core.validators.MinValueValidator(0)])),
                ('yield_stress', models.FloatField(help_text='Calculated yield stress (N/mm²)', validators=[django.core.validators.MinValueValidator(0)])),
                ('tensile_stress', models.FloatField(help_text='Calculated tensile stress (N/mm²)', validators=[django.core.validators.MinValueValidator(0)])),
                ('division_type', models.CharField(help_text='Division type classification', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stress_calculations', to='excelexport.inspectionreport')),
                ('sample_parameters', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stress_calculations', to='excelexport.sampleparameters')),
            ],
            options={
                'verbose_name': 'Stress Calculation',
                'verbose_name_plural': 'Stress Calculations',
                'ordering': ['-created_at'],
            },
        ),
    ]
